#!/bin/sh 

iptables -F 
iptables -X 

iptables -t nat -A POSTROUTING -o enp0s9 -j MASQUERADE 

iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP 

# ssh
iptables -A FORWARD -i enp0s3 -o enp0s8 -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT 
iptables -A FORWARD -i enp0s8 -o enp0s3 -p tcp --sport 80 -m state --state ESTABLISHED -j ACCEPT 

# http 
iptables -A FORWARD -i enp0s3 -o enp0s8 -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i enp0s8 -o enp0s3 -p tcp --sport 80 -m state --state ESTABLISHED -j ACCEPT 

# icmp 
iptables -A INPUT -i enp0s8 -p icmp --icmp-type echo-request -j ACCEPT 
ipatbles -A OUTPUT -o enp0s8 -p icmp --icmp-type echo-reply -j ACCEPT 
iptables -A INPUT -i enp0s3 -p icmp --icmp-type echo-request -j ACCEPT 
iptables -A OUTPUT -o enp0s3 -p icmp --icmp-type echo-reply -d 10.0.0.10 -j ACCEPT 
iptables -A OUTPUT -o enp0s3 -p icmp --icmp-type echo-reply -d 192.168.0.100 -j ACCEPT 
